version: '3.3'
services:
    subcons:
        image: nanjiang/subcons
        container_name: subcons
        environment:
            - USER_ID=${USER_ID}
        volumes:
            - ${DATA_DIR}:/data
            - ${SCRATCH_DIR}:/scratch
            - ${WEB_STATIC}:/static
        restart: always
        stdin_open: true
        tty: true

    topcons2:
        image: nanjiang/topcons2
        container_name: topcons2
        environment:
            - USER_ID=${USER_ID}
        volumes:
            - ${DATA_DIR}:/data
            - ${SCRATCH_DIR}:/scratch
            - ${WEB_STATIC}:/static
        restart: always
        stdin_open: true
        tty: true

    proq3:
        image: nanjiang/proq3
        container_name: proq3
        environment:
            - USER_ID=${USER_ID}
        volumes:
            - ${BLASTDB_DIR}:/app/proq3/database/blastdb
            - ${ROSETTA_DIR}:/app/proq3/apps/rosetta
            - ${SCRATCH_DIR}:/scratch
            - ${WEB_STATIC}:/static
        restart: always
        stdin_open: true
        tty: true

    boctopus2:
        image: nanjiang/boctopus2
        container_name: boctopus2
        environment:
            - USER_ID=${USER_ID}
        volumes:
            - ${DATA_DIR}:/data
            - ${SCRATCH_DIR}:/scratch
            - ${WEB_STATIC}:/static
        restart: always
        stdin_open: true
        tty: true

    pathopred:
        image: nanjiang/pathopred
        container_name: pathopred
        environment:
            - USER_ID=${USER_ID}
        volumes:
            - ${BLASTDB_DIR}:/blastdb
            - ${SCRATCH_DIR}:/scratch
            - ${WEB_STATIC}:/static
        restart: always
        stdin_open: true
        tty: true

    predzinc:
        image: nanjiang/predzinc
        container_name: predzinc
        environment:
            - USER_ID=${USER_ID}
        volumes:
            - ${DATA_DIR}:/data
            - ${DATA_DIR}/db_predzinc:/app/predzinc/data
            - ${SCRATCH_DIR}:/scratch
            - ${WEB_STATIC}:/static
        restart: always
        stdin_open: true
        tty: true
